# 程序相关部分

OUTPUT	:= mytest
SRCS	:= mytest.cpp tinyxml.cpp tinyxmlparser.cpp tinyxmlerror.cpp tinystr.cpp
DEBUG	:= NO
PROFILE	:= NO
LIBS	:=
INCS	:=

# 平台相关部分

CC	:= gcc
CXX	:= g++
LD	:= g++
AR	:= ar rc
RANLIB	:= ranlib

# 公共部分

DEBUG_CFLAGS	:= -Wall -Wno-format -g -DDEBUG
RELEASE_CFLAGS	:= -Wall -Wno-unknown-pragmas -Wno-format -O3

DEBUG_CXXFLAGS	:= ${DEBUG_CFLAGS}
RELEASE_CXXFLAGS:= ${RELEASE_CFLAGS}

DEBUG_LDFLAGS	:= -g
RELEASE_LDFLAGS :=

ifeq (YES, ${DEBUG})
	CFLAGS	:= ${DEBUG_CFLAGS}
	CXXFLAGS:= ${DEBUG_CXXFLAGS}
	LDFLAGS	:= ${DEBUG_LDFLAGS}
else
	CFLAGS	:= ${RELEASE_CFLAGS}
	CXXFLAGS:= ${RELEASE_CXXFLAGS}
	LDFLAGS	:= ${RELEASE_LDFLAGS}
endif

ifeq (YES, ${PROFILE})
	CFLAGS	:= ${CFLAGS} -pg -O3
	CXXFLAGS:= ${CXXFLAGS} -pg -O3
	LDFLAGS	:= ${LDFLAGS} -pg
endif

all: ${OUTPUT}

OBJS := $(addsuffix .o,$(basename ${SRCS}))

${OUTPUT}: ${OBJS}
	${LD} -o $@ ${LDFLAGS} ${OBJS} ${LIBS}

%.o : %.cpp
	${CXX} -c ${CXXFLAGS} ${INCS} $< -o $@

%.o : %.c
	${CC} -c ${CFLAGS} ${INCS} $< -o $@

clean:
	-rm -f ${OBJS} ${OUTPUT}

depend:
	makedepend ${INCS} ${SRCS}# DO NOT DELETE

mytest.o: /usr/include/stdio.h /usr/include/features.h /usr/include/libio.h
mytest.o: /usr/include/_G_config.h /usr/include/wchar.h tinyxml.h
mytest.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/xlocale.h
mytest.o: /usr/include/stdlib.h /usr/include/alloca.h /usr/include/string.h
mytest.o: /usr/include/assert.h tinystr.h
tinyxmlparser.o: /usr/include/ctype.h /usr/include/features.h
tinyxmlparser.o: /usr/include/endian.h /usr/include/xlocale.h tinyxml.h
tinyxmlparser.o: /usr/include/stdio.h /usr/include/libio.h
tinyxmlparser.o: /usr/include/_G_config.h /usr/include/wchar.h
tinyxmlparser.o: /usr/include/stdlib.h /usr/include/alloca.h
tinyxmlparser.o: /usr/include/string.h /usr/include/assert.h tinystr.h
tinyxmlerror.o: tinyxml.h /usr/include/ctype.h /usr/include/features.h
tinyxmlerror.o: /usr/include/endian.h /usr/include/xlocale.h
tinyxmlerror.o: /usr/include/stdio.h /usr/include/libio.h
tinyxmlerror.o: /usr/include/_G_config.h /usr/include/wchar.h
tinyxmlerror.o: /usr/include/stdlib.h /usr/include/alloca.h
tinyxmlerror.o: /usr/include/string.h /usr/include/assert.h tinystr.h
tinystr.o: tinystr.h /usr/include/assert.h /usr/include/features.h
tinystr.o: /usr/include/string.h /usr/include/xlocale.h
